version: '3'
services:
  loadbalancer:
    build: ./haproxy
    ports:
     - 80:80
    networks:
     - net
  app1:
    build: ./drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always
    networks:
     - net
  app2:
    build: ./drupal
    ports:
      - 8081:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    networks:
     - net
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
     - net
networks:
  net:
volumes: 
  pgdata:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:

